# Generated by Django 3.1.7 on 2021-04-06 06:17

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('acc_id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=256)),
                ('balance', models.FloatField(default=0.01)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('amount', models.FloatField()),
                ('remark', models.CharField(default='No message', max_length=256)),
                ('record_date', models.DateTimeField(default=datetime.datetime(2021, 4, 6, 6, 17, 14, 467215, tzinfo=utc), verbose_name='date recorded')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to='aiuts.user')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='aiuts.user')),
            ],
        ),
    ]
