# Generated by Django 3.1.7 on 2021-04-09 01:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aiuts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='record_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date recorded'),
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('acc_id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('balance', models.FloatField(default=0.01)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
