# Generated by Django 3.1.7 on 2021-04-13 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiuts', '0006_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('TU', 'Top Up'), ('ROP', 'Request of Payment'), ('NOR', 'Normal Transaction')], default='NOR', max_length=100),
        ),
        migrations.DeleteModel(
            name='Pending',
        ),
    ]
