# Generated by Django 3.1.7 on 2021-04-14 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiuts', '0007_auto_20210413_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('Top Up', 'TU'), ('Request of Payment', 'ROP'), ('Normal Transaction', 'NOR')], default='NOR', max_length=20),
        ),
    ]
