# Generated by Django 3.1.7 on 2021-04-14 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiuts', '0008_auto_20210414_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('Top Up', 'TU'), ('Request of Payment', 'ROP'), ('Normal Transaction', 'NOR')], default='Normal Transaction', max_length=20),
        ),
    ]
